[package]
name = "nacfahi"
version = "0.1.0"
edition = "2021"

[dependencies]
generic-array = "1.1.0"
num-traits = { version = "0.2.19", default-features = false, features = ["libm"] }
typenum = { version = "1.17.0", features = ["no_std", "const-generics"] }

[lints]
workspace = true

[package.metadata.docs.rs]
rustdoc-args = [ "--html-in-header", "katex.html" ]
